return {
  {
    "sphamba/smear-cursor.nvim",
    event = "VeryLazy",
    cond = vim.g.neovide == nil,
    keys = {
      { "<leader>uC", "<cmd>SmearCursorToggle<cr>", desc = "Toggle Cursor Animation" },
    },
    opts = {
      cursor_color = "none",
      hide_target_hack = true,
      never_draw_over_target = true,
      time_interval = 8,
      smear_between_buffers = true,
      smear_between_neighbor_lines = true,
      smear_horizontally = true,
      smear_vertically = true,
      smear_diagonally = true,
      min_horizontal_distance_smear = 0,
      min_vertical_distance_smear = 0,
      stiffness = 0.5,
      trailing_stiffness = 0.4,
      stiffness_insert_mode = 0.5,
      trailing_stiffness_insert_mode = 0.4,
      anticipation = 0,
      damping = 0.92,
      damping_insert_mode = 0.92,
      distance_stop_animating = 0.03,
      filetypes_disabled = {
        "snacks_dashboard",
        "snacks_terminal",
        "TelescopePrompt",
      },
    },
  },

  {
    "karb94/neoscroll.nvim",
    event = "VeryLazy",
    opts = {
      hide_cursor = true,
      stop_eof = true,
      respect_scrolloff = true,
      cursor_scrolls_alone = true,
      duration_multiplier = 0.7,
      easing = "quadratic",
      mappings = {
        "<C-u>",
        "<C-d>",
        "<C-b>",
        "<C-f>",
        "<C-y>",
        "<C-e>",
        "zt",
        "zz",
        "zb",
      },
    },
  },
}
